pipeline {
    agent any

    stages {
        stages {
        stage('compile') {
            steps {
                sh 'mvn clean compile' 
            }
        }
 	}
        stages {
        stage('Test') {
            steps {
                sh 'mvn clean test' 
            }
        }
    }
  }
}